# CMake generated Testfile for 
# Source directory: /workspaces/algokit-graph
# Build directory: /workspaces/algokit-graph/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BFS]=] "/workspaces/algokit-graph/build-asan/test_bfs")
set_tests_properties([=[BFS]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;203;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[DFS]=] "/workspaces/algokit-graph/build-asan/test_dfs")
set_tests_properties([=[DFS]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;223;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[ConnectedComponents]=] "/workspaces/algokit-graph/build-asan/test_connected_components")
set_tests_properties([=[ConnectedComponents]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;243;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[CycleDetection]=] "/workspaces/algokit-graph/build-asan/test_cycle_detection")
set_tests_properties([=[CycleDetection]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;263;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[DirectedCycleDetection]=] "/workspaces/algokit-graph/build-asan/test_directed_cycle_detection")
set_tests_properties([=[DirectedCycleDetection]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;284;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[TopologicalSort]=] "/workspaces/algokit-graph/build-asan/test_topological_sort")
set_tests_properties([=[TopologicalSort]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;305;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[KahnTopologicalSort]=] "/workspaces/algokit-graph/build-asan/test_kahn_topological_sort")
set_tests_properties([=[KahnTopologicalSort]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;326;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[ShortestPath]=] "/workspaces/algokit-graph/build-asan/test_shortest_path")
set_tests_properties([=[ShortestPath]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;346;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[Dijkstra]=] "/workspaces/algokit-graph/build-asan/test_dijkstra")
set_tests_properties([=[Dijkstra]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;388;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[BellmanFord]=] "/workspaces/algokit-graph/build-asan/test_bellman_ford")
set_tests_properties([=[BellmanFord]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;408;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[FloydWarshall]=] "/workspaces/algokit-graph/build-asan/test_floyd_warshall")
set_tests_properties([=[FloydWarshall]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;428;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[DisjointSet]=] "/workspaces/algokit-graph/build-asan/test_disjoint_set")
set_tests_properties([=[DisjointSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;448;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[Kruskal]=] "/workspaces/algokit-graph/build-asan/test_kruskal")
set_tests_properties([=[Kruskal]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;468;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[Prim]=] "/workspaces/algokit-graph/build-asan/test_prim")
set_tests_properties([=[Prim]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;488;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[StronglyConnectedComponents]=] "/workspaces/algokit-graph/build-asan/test_strongly_connected_components")
set_tests_properties([=[StronglyConnectedComponents]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;508;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
add_test([=[Graph]=] "/workspaces/algokit-graph/build-asan/test_graph")
set_tests_properties([=[Graph]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/algokit-graph/CMakeLists.txt;528;add_test;/workspaces/algokit-graph/CMakeLists.txt;0;")
